ConsolePlayers:
  - NaysKutzu
  - Alice152
  - Alexutzerion5
LockedConsoleCommands:
  - plugman
Messages:
  # Prefix
  Prefix: "&c&lNoxl&f&lCraft &7>"
  NoPermission: "You do not have any permissions to run this command!"
  # Console
  Syntax: "Use: /console [Command]"
  LockedCommand: "This command is blocked!"
  Complete: "The command has been executed in the server console!!"
  # Join Messages
  JoinMessage: "%player% has joined the server!"
  LeaveMessage: "%player% has left the server!"
  # AntiUserSteal
  AntiUserSteal: "Why you trying to steal an user account?"

Database:
  host: 127.0.0.1
  port: 3306
  username: "root"
  password: ""
  database: ""